Validate context if there is any of the requested space types available
nutti/Magic-UV pull request #138
Opened 2020-10-16 14:15 UTC by MatthiasThDs

I put this function into common:

def is_valid_space(context, allowed_spaces):
    for area in context.screen.areas:
        for space in area.spaces:
            if space.type in allowed_spaces:
                return True
    return False

And use it in all the operators.

2020-10-17 01:37 UTC, nutti requested changes
Thanks for your great contribution and improvements.
Some CI tests are failed because of the invalid code format.

Could you fix them?

2020-10-17 01:37 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
> -
Please do not delete this line?

2020-10-17 01:37 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
> -
Please do not delete this line?

2020-10-17 01:37 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
> -    # after the execution
I think this change makes the CI fail.
Could you delete the spaces following this comment?

2020-10-17 01:37 UTC, nutti commented on src/magic_uv/op/copy_paste_uv.py
> +    if not common.is_valid_space(context, ['IMAGE_EDITOR', 'VIEW_3D']):
I think this operation should be executed only in View3D.

```suggestion
    if not common.is_valid_space(context, ['VIEW_3D']):
```

2020-10-17 02:35 UTC, nutti commented
@MatthiasThDs 

BTW, I will add your name to [here](https://github.com/nutti/Magic-UV#project-authors) and [here](https://github.com/nutti/Magic-UV/blob/master/src/magic_uv/__init__.py#L29-L31) after this PR is merged.
Do you have any requests about your name?

If you don't have any requests, I will add @MatthiasThDs (MatthiasThDs) to there.

2020-10-19 07:48 UTC, MatthiasThDs commented
Hi,
yes MatthiasThDs is absolutely ok.

2020-10-19 09:28 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
> +    # after the execution
```suggestion
    # after the execution
```

2020-10-19 09:29 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
```suggestion


```

2020-10-19 09:29 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
```suggestion

```

2020-10-19 09:29 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
```suggestion


```

2020-10-19 09:34 UTC, nutti requested changes
@MatthiasThDs 

Thanks.
Could you apply these suggestion?
I could not merge your PR if these suggestions are not approved.

2020-10-19 09:34 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
```suggestion


```

2020-10-19 09:34 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
```suggestion


```

2020-10-19 09:35 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
>  from ..utils import compatibility as compat
```suggestion
from ..utils import compatibility as compat


```

2020-10-19 09:35 UTC, nutti commented on src/magic_uv/op/align_uv_cursor.py
```suggestion


```

2020-10-19 10:27 UTC, nutti requested changes
@MatthiasThDs 

Thanks.
Sorry, the CI still error because of the lack of blank line.
Could you apply these suggestions?

2020-10-19 10:27 UTC, nutti commented on src/magic_uv/common.py
```suggestion


```

2020-10-19 10:27 UTC, nutti commented on src/magic_uv/common.py
```suggestion


```

2020-10-19 11:10 UTC, MatthiasThDs commented
I hope we could make it.
Sry for having the wrong white spaces.
Thank you very much for your support on this issue!

2020-10-19 11:23 UTC, nutti approved these changes
LGTM, thanks for your great contribution!

2020-10-19 11:24 UTC, merged

2020-10-19 11:25 UTC, nutti commented
@MatthiasThDs 

Merged this PR. Thanks for great work!