Texture wrap fixes
nutti/Magic-UV pull request #163
Opened 2022-09-12 16:55 UTC by c-d-a

Currently, texture wrap (refer/set) only reliably works for rectangular faces that have perfect undistorted UVs.  

https://user-images.githubusercontent.com/55441216/189711926-30a6be62-e73f-434e-976c-54914719284d.mp4  

The first commit addresses flaws in the existing algorithm. Mainly, it takes into account the fact that projections of original face's third vert and of target face's third vert don't necessarily both lie in the same direction relative to a shared reference vert.

With this fixed, it now works for faces of arbitrary shape. However, it still requires perfect UVs, and something as simple as a non-square texture with aspect-corrected unwrap would break everything.

https://user-images.githubusercontent.com/55441216/189711997-973d12c5-ac49-48fa-8b6b-8e6b1781d9e7.mp4

You can only get so far with rotation and scale, so the second commit replaces the algorithm with one based on finding an affine transformation between spaces. Now it should work reasonably well for arbitrary meshes and UVs.

https://user-images.githubusercontent.com/55441216/189712039-b3a1acb9-0692-47b8-83be-0cf357de101b.mp4

2022-09-16 17:01 UTC, c-d-a commented
Added fixes for the failing pylint check.
Added a fix for reference faces with three or more collinear verts.

2022-09-16 23:37 UTC, c-d-a commented
More lint fixes (pylint 2.15.2 didn't catch these)  
I've restored the extra collinearity check. Don't know how you feel about arbitrary precision checks like that, but it helps avoid some cases where precision error alone is enough to find a nonsense solution.

2022-09-17 08:14 UTC, nutti requested changes
Thanks for your great contribution!
This enhancement will improve the user's workflow.

I have minor comments for your patch.
Could you check them?

2022-09-17 08:14 UTC, nutti commented on src/magic_uv/op/texture_wrap.py
> +            tform_mtx = None
Could you use change the variable name to `transform_matrix` to clear the intention of usage?

2022-09-17 08:14 UTC, nutti commented on src/magic_uv/op/texture_wrap.py
> +                    continue
Is it possible to change the hard coded value to the constant variable for changing this value easily in future?

2022-09-17 08:14 UTC, nutti commented on src/magic_uv/op/texture_wrap.py
> +                d_3d = info["vert"].co
Could you also add the comment here like L240-L242 for the explanation of the algorithm?

2022-09-18 00:08 UTC, nutti approved these changes
LGTM

Thanks for your contribution! @c-d-a

2022-09-18 00:12 UTC, merged

2022-09-18 06:13 UTC, nutti commented
@c-d-a 

You can add your name to the `author` field.

https://github.com/nutti/Magic-UV/blob/master/src/magic_uv/__init__.py#L13-L16

If you want to add your name, please tell me the name.

2022-09-19 02:05 UTC, c-d-a commented
@nutti
I sign things as "chedap".

2022-10-24 09:01 UTC, nutti commented
@c-d-a 

I added your name to the author field.
Thanks for your contribution!

2024-03-13 09:09 UTC, c-d-a commented
Turns out there is a builtin for this stuff. Everything from line 186 to line 303 can be replaced with a "tgt_face.copy_from_face_interp((ref_face,))". It will pass all of the examples above, and won't even require the two faces to share an edge.

The catch: it works by projecting from the reference face, so it only works for flattish surfaces and completely breaks on corners. And also, it interpolates not just UVs but everything else too (vertex colors, armature weights, etc).

The syntax is weird (wrapping the face into a tuple), and nobody appears to have ever used it for anything ever, so I just thought I'd document it for posterity.